"""create status colum in todos table 

Revision ID: a9547deab902
Revises: fee8fe20a4a8
Create Date: 2025-02-24 21:10:58.216304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9547deab902'
down_revision: Union[str, None] = 'fee8fe20a4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos_table', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos_table', 'status')
    # ### end Alembic commands ###
